#!/usr/bin/env bash
#Bash script that will display information about subdomains.

dig_information () {
    info=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:'|tail -1|awk '{print $(NF-1) "  "  $(NF)}')
    echo "$2 $info" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 2 ]
then
    dig_information "$1" "$2"
elif [ "$#" == 1 ]
then
     dig_information "$1" "www"
     dig_information "$1" "lb-01"
     dig_information "$1" "web-01"
     dig_information "$1" "web-02"
fi
