#!/usr/bin/env bash
#script that transfers a file from our local computer to a server
#run script with 4 arguements

#Check if number of arguements is less than 3
if [ $# -lt 3 ]
then
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi 
