#!/usr/bin/env bash
#Script to install nginx web server on ubuntu server
#Has a custom header i.e X-Served-by HOSTNAME

apt-get update
apt-get upgrade
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" >> /var/www/html/index.html
sed -i "40i\add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
