#!/usr/bin/env bash
#Script to install nginx web server on ubuntu server
#Responds with a string "Holberton School" when it receives a GET request
#/redirect_me redirects user to another page
#Has a custom header i.e X-Served-by HOSTNAME

sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Holberton School" >> /var/www/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    add_header X-Served-By \$hostname;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
