#!/usr/bin/env bash
#Script to install nginx web server on ubuntu server
#Has a custom header i.e X-Served-by HOSTNAME

apt-get update
apt-get upgrade
apt-get -y install nginx
sed -i "11i\add_header X-Served-By $HOSTNAME/" etc/nginx/nginx.conf
service nginx restart
