#!/usr/bin/env bash
#Installs and configures HAproxy on lb-01 server

#install HAProxy version 2.0
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get update
apt-get install haproxy=2.0.\*

#enable HAProxy to be started by init script
echo "ENABLED=1" >> /etc/default/haproxy

#move default configuration file and create new on
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

#add configuration to new file
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen load_balancer 
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 38-web-01 34.73.50.31:80 check
    server 38-web-02 34.73.156.72:80 check
" >> /etc/haproxy/haproxy.cfg

#start HAProxy service
service haproxy start
