#!/usr/bin/env bash
#Configures nginx to listen on port 80 and stops nginx.service completely

sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /var/run/nginx.pid
