#!/usr/bin/env bash
#Displays "Holberton School" ten times and "Hi" at the 9th iteration
i=0

while [ $i -lt 10 ]
do
    if [ $i -eq 9 ]
    then
       echo "Hi"
    fi
    echo "Holberton School"
    (( i++ ))
done
