#!/usr/bin/env bash
#Loops from 1 to 10 displaying "Holberton School"
#displays "bad luck" at the 4th iteration
#displays "good luck" on the 8th iteration

i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
        echo "bad luck"
    elif [ $i -eq 7 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    (( i++ ))
done
