#!/usr/bin/env bash
# Installs ufw on server and sets up few rules.

sudo apt-get -y install ufw
sudo ufw disable
sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
sudo ufw enable
